export const SEND_CURRENT_REQUEST='SEND_CURRENT_REQUEST';
 export const SEND_CURRENT_REQUEST_SUCCESS='SEND_CURRENT_REQUEST_SUCCESS';
 export const SEND_CURRENT_REQUEST_FAILURE='SEND_CURRENT_REQUEST_FAILURE'